services:
  lead-gen-db:
    image: postgres:17
    restart: always
    ports:
      - "2345:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: lead_gen_db
      POSTGRES_USER: lead_gen_user
      POSTGRES_PASSWORD: lead_gen_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U lead_gen_user -d lead_gen_db" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  lead-gen-backend:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: main.py
      FLASK_RUN_HOST: 0.0.0.0
      POSTGRES_DB: lead_gen_db
      POSTGRES_USER: lead_gen_user
      POSTGRES_PASSWORD: lead_gen_password
      POSTGRES_HOST: lead-gen-db
      POSTGRES_PORT: 5432
      GOOGLE_APPLICATION_CREDENTIALS: /app/service-account.json
    volumes:
      - ./backend/service-account.json:/app/service-account.json
    depends_on:
      lead-gen-db:
        condition: service_healthy
    restart: always

volumes:
  pgdata:
