services:
  db:
    image: postgres:17
    networks:
      - lead-gen-prod-network
    restart: always
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: lead_gen_prod_db 
      POSTGRES_USER: lead_gen_prod_user
      POSTGRES_PASSWORD: lead_gen_prod_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U lead_gen_prod_user -d lead_gen_prod_db" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  backend:
    image: ${IMAGE_REF} 
    networks:
      - lead-gen-prod-network
    pull_policy: always
    ports:
      - "5050:5050"
    env_file:
      - ./backend/.env.prod          # Injects ALL vars (incl. DATABASE_URL) into the container
    environment:
      # These override anything in .env if needed
      DATABASE_URL: postgresql://lead_gen_prod_user:lead_gen_prod_password@db:5432/lead_gen_prod_db
      GOOGLE_APPLICATION_CREDENTIALS: /app/service-account.json
      API_URL: https://lead-gen.adept-techno.co.ke
      AUTH0_DOMAIN: dev-2685h5q7efjt6peh.us.auth0.com
      AUTH0_API_AUDIENCE: https://api.presti
    volumes:
      - ./backend/service-account.json:/app/service-account.json
    depends_on:
      db:
        condition: service_healthy
    restart: always

networks:
  lead-gen-prod-network:
    driver: bridge

volumes:
  pgdata_prod:
    external: true
    name: lead_gen_prod_pgdata
